### ISSUE TITLE
a problem  with reading the vtu file

### ISSUE THREAD

**Issue by JWleo** [phmkopp/vtu11#56]
i had used the tinyxml2 to read vtu file ,and the data in vtu file was Appended  in format of binary.

then the tinyxml2 can't read the xml data in vtu file . 

 Can i read the vtu with other methods ?

**Comment by phmkopp** [comment]
You might want to write in ascii format since it is the easiest and can also be understood by just looking at it. Raw binary breaks the xml standard, which is why there is a base64 encoded binary format that exists inline (in the xml data blocks) or appended (data comes afterwards). So base64 appended may also be an option, but you'll have to decode the data after reading it.

**Comment by JWleo** [comment]
yeah, i know it @phmkopp
